apiVersion: v1
kind: Service
metadata:
  name: tripwire
  labels:
    app: tripwire
spec:
  type: NodePort
  selector:
    app: tripwire
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
